### PR TITLE
corrected the link

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
I have corrected the netlify link

### CODE REVIEW

**Comment by balayokesh** [comment]
> I have corrected the netlify link

Thanks bro.  There are some conflicts while merging.  I will resolve it and merge your pull request by today evening

**Comment by Jassi10000-zz** [comment]
> > I have corrected the netlify link
> 
> Thanks bro. There are some conflicts while merging. I will resolve it and merge your pull request by today evening

Sure no issues , what are merge conflicts ?

**Comment by balayokesh** [comment]
> > > I have corrected the netlify link
> > 
> > 
> > Thanks bro. There are some conflicts while merging. I will resolve it and merge your pull request by today evening
> 
> Sure no issues , what are merge conflicts ?

README.md is the conflicting file

**Comment by Jassi10000-zz** [comment]
@yokesh004 Ohh , do tell if you need any help

**Pull request merged**
